# Site settings
title: Yu-Cheng Chuangâ€™s Blog
author: Yu-Cheng Chuang
email: ducksteven@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yu-Cheng Chuang's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.yorkxin.org" # the base hostname & protocol for your site
twitter_username: yorkxin
github_username:  chitsaou
disqus_shortname: chitsaou
feedburner_url: https://feeds.feedburner.com/chitsaou

google_analytics_id: UA-27155466-1

permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge

gems:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
