# Site settings
title: Yu-Cheng Chuang
email: ducksteven@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yu-Cheng Chuang's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.yorkxin.org" # the base hostname & protocol for your site
twitter_username: yorkxin
github_username:  chitsaou

permalink: :year/:month/:day/:title/

gems:
- jekyll-html-pipeline
- markdown-highlight-extended-filter

# Build settings
markdown: HTMLPipeline

html_pipeline:
  filters:
    - "MarkdownHighlightExtendedFilter"
    - "markdownfilter"
